const FALLBACK_FACTORY_PROGRAM_ID = "GoPZh3S6q3K4XqEZPBSKo3qJ5PWYcdHiR4wrMX6si4kn";
const FALLBACK_ORACLE_PROGRAM_ID = "AoZnjiFNkMH2mGKUfqoF6PTaoUMK4H4GbwXva5Jg1RGz";
const FALLBACK_TRADING_PROGRAM_ID = "8n4jg5QajLtAsAVVvZpKSuuMV7JNELpgQqz7oisWhXpt";

export const SOLANA_RPC_URL =
  Deno.env.get("SOLANA_RPC_URL") ?? "http://127.0.0.1:8899";

export const TREND_FACTORY_PROGRAM_ID =
  Deno.env.get("TREND_FACTORY_PROGRAM_ID") ?? FALLBACK_FACTORY_PROGRAM_ID;
export const TREND_ORACLE_PROGRAM_ID =
  Deno.env.get("TREND_ORACLE_PROGRAM_ID") ?? FALLBACK_ORACLE_PROGRAM_ID;
export const TREND_TRADING_PROGRAM_ID =
  Deno.env.get("TREND_TRADING_PROGRAM_ID") ?? FALLBACK_TRADING_PROGRAM_ID;
